# Generated by Django 2.0.4 on 2018-04-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='team_id',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='team_name',
            field=models.CharField(default='Paas', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
