# Generated by Django 2.0.3 on 2018-03-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180321_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='person_name',
            field=models.CharField(default='2018-03-10', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift_name',
            field=models.CharField(default='2018-10-10', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(),
        ),
    ]
